version: "3.8"
services:
  mongo:
    image: mongo:6-jammy
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: root

  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - mongo
    environment:
      PORT: 5000
      DATABASE_URI: mongodb://user:root@mongo:27017/grants?authSource=admin
      CLIENT_URI: http://localhost:5173
    ports:
      - "5000:5000"
    command: npm run start

  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - server
    command: npm run dev -- --host
    ports:
      - "5173:5173"
